[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "gunicorn app:app"
healthcheckPath = "/"
healthcheckTimeout = 300

[nixpacks]
python-version = "3.10"

[variables]
PYTHON_VERSION = "3.10.0" 